In [ ]:
from sklearn.preprocessing import LabelEncoder

items = ["냉장고","TV","컴퓨터","선풍기","선풍기", "에어컨", "에어컨"]

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print(labels)

#알아서 숫자를 인코딩함.

[1 0 4 2 2 3 3]


In [ ]:
print(encoder.classes_) # 어떻게 숫자별 라벨이 됫는지 보여줌.

['TV' '냉장고' '선풍기' '에어컨' '컴퓨터']


In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np


items = ["냉장고","TV","컴퓨터","선풍기","선풍기", "에어컨", "에어컨"] # 7개

items = np.array(items).reshape(-1,1) # 2차원 배열로 바꿈

oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)

print(oh_labels.toarray())
print(oh_labels.shape)




[[0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]]
(7, 5)


In [6]:
import pandas as pd

df = pd.DataFrame({"item": ["냉장고","TV","컴퓨터","선풍기","선풍기", "에어컨", "에어컨"]})
print(df)
pd.get_dummies(df)

  item
0  냉장고
1   TV
2  컴퓨터
3  선풍기
4  선풍기
5  에어컨
6  에어컨


,item_TV,item_냉장고,item_선풍기,item_에어컨,item_컴퓨터
0,False,True,False,False,False
1,True,False,False,False,False
2,False,False,False,False,True
3,False,False,True,False,False
4,False,False,True,False,False
5,False,False,False,True,False
6,False,False,False,True,False
