In [1]:
# reshape
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6])
print(arr.shape)
print(arr.size)

(6,)
6


In [7]:
reshaped = arr.reshape((2,3))

In [9]:
print(reshaped.shape)
print(reshaped)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [10]:
# astype
## 데이터타입을 변경한다.

arr = np.array([1,2,3,4,5,6])
float_arr = arr.astype(float)
print(float_arr)

[1. 2. 3. 4. 5. 6.]


In [12]:
# ravel
## 다차원의 배열을 1차원 배열로 변경.

arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape((2,3))
print(reshaped)

raveled = reshaped.ravel()
print(raveled)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
# flatten
## 다차원 배열을 1차원 배열로 평탄화 하는것.

arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr)
flattended = arr.flatten()
print(flattended)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [16]:
# transpose
## 배열의축을 바꾸는 함수

arr = np.array([
    [1,2,3],
    [4,5,6]
])

transposed = arr.transpose()
print(transposed)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# 수학 연산 -> 각 요소끼리 연산작용

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1+arr2)
print(arr1*arr2)

[5 7 9]
[ 4 10 18]


In [23]:
# 배열 간 비교 연산

arr1 = np.array([5,3,3])
arr2 = np.array([1,2,6])

print(arr1 > arr2)
print(arr1 == arr2)
print(arr1 != arr2)

[ True  True False]
[False False False]
[ True  True  True]


In [25]:
# 배열 간 논리 연산

arr1 = np.array([True, False, True])
arr2 = np.array([False, True, True])

print(arr1&arr2)
print(arr1|arr2)

[False False  True]
[ True  True  True]


In [ ]:
# 배열 간 집계연산

arr = np.array([1,2,3,4,5])
print(arr.sum())
print(arr.mean()) # 평균값
print(arr.min())
print(arr.max())

15
3.0
1
5


In [29]:
arr = np.array([1,2,3,4,5])
scalar = 2
print(arr * scalar)

[ 2  4  6  8 10]
